baseURL = "https://kvammeselvik.github.io/"
languageCode = "no-nn"
title = "Kvamme/Selvik"
theme = "mainroad"
publishDir = "public"
# paginate = "10"

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true

[Params]
  description = "On livet i familien Kvamme/Selvik. Kanskje mest om Aasmund." # Site description. Used in meta description
  # copyright = "John Doe" # Footer copyright holder, otherwise will use site title
  opengraph = false # Enable OpenGraph
  schema = false # Enable Schema
  twitter_cards = false # Enable Twitter Cards if true
  readmore = false # Show "Read more" button in list if true
  # authorbox = true # Show authorbox at bottom of pages if true
  toc = true # Enable Table of Contents
  pager = true # Show pager navigation (prev/next links) at the bottom of pages if true
  post_meta = ["author", "date", "categories", "translations"] # Order of post meta information
  mainSections = ["post", "blog", "news"] # Specify section pages to show on home page and the "Recent articles" widget
  dateformat = "2006-01-02" # Change the format of dates
  mathjax = true # Enable MathJax
  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path
  mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
  googleFontsLink = "https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700" # Load Google Fonts
  # customCSS = ["css/custom.css"] # Include custom CSS files
  # customJS = ["js/custom.js"] # Include custom JS files