#+TITLE: Matematikk på nettsider
#+DATE: 2025-10-26
#+tags[]: mathjax latex
#+categories[]: skriving matematikk
#+HUGO_SECTION: posts
#+HUGO_BASE_DIR: //wsl.localhost/Ubuntu-22.04/home/aasmund/kvammeselvik
* Innleiing
Det er notorisk vanskeleg å skrive matematikk og tekst saman. Vanleg tekst er /eindimensjonal/ i den forstand at teksten flyt i ei retning (langs tekstlina). At vi bryt teksten inn i separate liner gjer ingen ting; alle linene er like høge, så tekstbiletet vert uniformt og harmonisk. Ingen bokstavar / symbol / teikn går høgare enn dei andre, eller lågare enn dei andre.

Når vi får inn ein matematisk formel vert alt litt annleis. Det er svært få matematiske uttrykk som held seg innanfor øvre og nedre grense for bokstavane. Berre sjå på dette: \\(\frac{1}{2}\\)x eller denne: \\(\int_0^k f(x)dx\\). Det eit godt typografisk verktøy (som \\(\LaTeX\\) gjer er å gje dei linene som treng det litt ekstra plass over og under, slik at ingen av dei matematiske formlane "stanger" borti kvarandre. 

Men det store problemet kjem når vi skal vise matematiske formlar på nettsider. Då må vi bruke JavaScriptet (?) 
