name: Deploy Hugo site to main branch

on:
  push:
    branches:
      - main               # trigger when you push to main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest"
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy to main branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.HEIMEMASKIN }}
          publish_dir: ./public
          publish_branch: main
          commit_message: "Deploy Hugo site (auto‑generated)"
